package com.djhu.hiup.message.server.service.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2018-05-25T08:41:25.843+08:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "urn:hl7-org:v3", name = "HIPMessageServerWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface HIPMessageServerWebServiceSoap {

    @WebResult(name = "HIPMessageServerResult", targetNamespace = "urn:hl7-org:v3")
    @RequestWrapper(localName = "HIPMessageServer", targetNamespace = "urn:hl7-org:v3", className = "com.djhu.hiup.message.server.service.webservice.HIPMessageServer")
    @WebMethod(operationName = "HIPMessageServer", action = "urn:hl7-org:v3HIPMessageServer")
    @ResponseWrapper(localName = "HIPMessageServerResponse", targetNamespace = "urn:hl7-org:v3", className = "com.djhu.hiup.message.server.service.webservice.HIPMessageServerResponse")
    public String hipMessageServer(
            @WebParam(name = "action", targetNamespace = "urn:hl7-org:v3")
            String action,
            @WebParam(name = "message", targetNamespace = "urn:hl7-org:v3")
            String message
    );
}
